[project]
name = "uni-bot"
version = "0.1.0"
description = "Add a short description here"
authors = ["Wiktor Jurkiewicz <watjurk@gmail.com>"]
channels = ["conda-forge"]
platforms = ["osx-arm64"]

[tasks]
start = "python ./src/main.py"


[dependencies]
python = "3.12.0.*"
thefuzz = "0.19.0.*"
